# Generated by Django 4.1.5 on 2023-02-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('vehicle_model', models.PositiveIntegerField()),
                ('owner', models.CharField(max_length=100)),
                ('km_driven', models.PositiveIntegerField()),
                ('date_of_purchase', models.DateField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('ev', 'ev')], max_length=100)),
            ],
        ),
    ]
