# Generated by Django 4.1.5 on 2023-03-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_vehicles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='price',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
