# Generated by Django 4.1.5 on 2023-03-19 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicles'),
        ),
    ]
