# Generated by Django 4.1.5 on 2023-04-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('follow_author', models.CharField(blank=True, max_length=2083)),
                ('book_available', models.BooleanField()),
            ],
        ),
    ]
