# Generated by Django 4.1.5 on 2023-03-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField()),
                ('slots', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
            ],
        ),
    ]
